language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.1
  - android-24
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
jdk:
- oraclejdk8
notifications:
  slack:
    secure: lf2X+YT/e8dKDMIGzmhzb6LiID7VvXpoylfLBuBT56hkzbCWFqQ94sEBzjU8Ha0o9JhH/CwME1sl3ZRWN5uRVJqzwD+spn03TQJ7wEd2pQCeONmRa3h8ulyvFtbB2F3gcfK/Yu22pEl6bPUOvf+niNgYO1G1w9hMW5IPMChqQzD7Hvw8vFNFcUmdMkCfRRx5IMML7LVJ6WuD8HTq9hhlyhGZXAoGOyzawIE0jzl0FddUAo1AR3p/wHOcYXlUYhAUGD9nRkhivhMiqaJQdtll8g0O5K9nZy6AKZm8nc99l9Ck7ktUvGz+8ESC665fvlbUrjJ470zvZebfNyVdj9u1JYFppZMqiRQ6gQn2j5ZxYlWupZEOHCMJJLLUa7LCz13ZpYYtu9elWwt/YQchZTmD8YwDGr5c7ly9W34rKqhBn0CsmnIEWQ27nTACBvB7ZupX/hq56LLPV1JqyUIEzEbRj4EIVLTKNNT2UEy5OTM9KROONRuIuHqJeuFDKMJvh7rNXXKbBUjIJP6/m5q8Kqf4tVRe8vDDBn1kz0tWToNNtICYL/JSWgztOf25750o1ZTF9uWtt0DZlt7GOOMGjex9A0Uob3jHQIsGvPYHqI5TUK7szKTrkRa14OIeM4KCq9PqBho4eFVtJjxuuBZqwheS9fpfEuwcehLLSUnGKgcdGSw=
